site_name: Digital Federalism
site_url: https://digital-federalism.org/
site_description: ''
docs_dir: docs
site_dir: site
use_directory_urls: true
strict: false
theme:
  name: null
  custom_dir: theme
  language: es
markdown_extensions:
- meta
- admonition
- attr_list
- def_list
- footnotes
- md_in_html
- tables
- toc
- pymdownx.superfences: {}
- pymdownx.details: {}
- pymdownx.smartsymbols: {}
extra:
  accent_color: '#d32f2f'
  current_year: '2026'
  nav_categories:
  - code: politica
    name: politica
    url: /categorias/politica/
    color: '#dc2626'
  - code: tecnologia
    name: tecnología
    url: /categorias/tecnologia/
    color: '#dc2626'
  - code: historia
    name: historia
    url: /categorias/historia/
    color: '#dc2626'
  twitter_handle: null
  contact_email: null
